lists:
  - name: "확장 & 기타 (Extensions & Others)"
    repos: []              # 명시 추가 (owner/name)
    include_keywords: ["extension","helper","toolkit","snk","gitanimals","build-your-own-x"]
    include_topics: []
    exclude_keywords: []

  - name: "자동화 (Automation)"
    repos: []
    include_keywords: ["github-actions","actions","runner","act","n8n","lefhook","mcp","opencode","codemod","resumable"]
    include_topics: ["actions","automation"]
    exclude_keywords: []

  - name: "웹 & 프론트엔드 (Web & Frontend)"
    repos: []
    include_keywords: ["react","next","mui","material","shadcn","tailwind","vercel","ui","form","rrweb","reveal","liquid-glass","base-ui","magicui","ai-elements","image-url","darkmode","ts-brand","lenses","velite","orval"]
    include_topics: ["react","nextjs","frontend","ui"]
    exclude_keywords: []

  - name: "인공지능 / 머신러닝 (AI / ML)"
    repos: []
    include_keywords: ["pytorch","llm","rag","gemma","litgpt","finetune","ner","generate-sequences","kbla","execu","simpletuner","marimo","verifiers","lotus","orbital","ml","agent","ai"]
    include_topics: ["machine-learning","deep-learning","llm","rag"]
    exclude_keywords: []

  - name: "리소스 / 자료 모음 (Resources)"
    repos: []
    include_keywords: ["awesome","list","profile-readme","devteam","dev-conf-replay","gallery","book"]
    include_topics: ["awesome-list"]
    exclude_keywords: []

  - name: "학습 & 스터디 (Learning & Study)"
    repos: []
    include_keywords: ["course","lecture","stat453","retreat","study","tutorial","QandAI","examples"]
    include_topics: ["course","lecture","education"]
    exclude_keywords: []

  - name: "디자인 & AI 연동 (Design & AI Integration)"
    repos: []
    include_keywords: ["figma","design","mcp","context"]
    include_topics: ["design","figma"]
    exclude_keywords: []

  - name: "백엔드 & 런타임 (Backend & Runtime)"
    repos: []
    include_keywords: ["nodejs","node","runtime"]
    include_topics: ["backend","runtime","nodejs"]
    exclude_keywords: []

  - name: "시각화 & 도구 (Visualization & Tool)"
    repos: []
    include_keywords: ["matplotlib","watermark","plot","fastplotlib","excalidraw"]
    include_topics: ["visualization","plot"]
    exclude_keywords: []

  - name: "데이터 & 처리 (Data & Processing)"
    repos: []
    include_keywords: ["sql","pandas","dataset","sklearn","notebook","lotus","orbital","matplotlib"]
    include_topics: ["data","pandas","sql"]
    exclude_keywords: []
